import type { EntityBase } from '../types/entity/Root'
import type { CreationOptional, EntityCreationAttributes } from '../types/entity/Creation'
import type { DialectOptions } from '../types/Config'
import type { EntityQueryable } from '../types/entity/Query'


/**
 * Base class that defines the contract every ORM manager must satisfy.
 *
 * An ORM manager wraps the raw database layer behind a small, typed
 * CRUD surface (`createOne`, `deleteOne`, `destroyAll`). It exposes a
 * single concrete instance (`manager`) plus the active {@link DialectOptions},
 * and leaves the actual database calls to subclasses that know the
 * specifics of one ORM (Sequelize today, Prisma-ready for the future).
 *
 * Subclasses implement the abstract methods to talk to their ORM's
 * native model API, while callers consume the typed entity shape `E`
 * regardless of which ORM is underneath.
 *
 * @typeParam E - The typed entity shape. Must extend {@link EntityBase}.
 * @typeParam T - The ORM-specific row / model type returned by `createOne`.
 *                Typically a Sequelize `Model` instance or a Prisma
 *                record. Left open (`T`) because every ORM has its own
 *                model type.
 * @typeParam M - The ORM-specific database manager type (e.g. a Sequelize
 *                `Sequelize` instance or a Prisma `PrismaClient`).
 *                Defaults to `unknown` — supply it explicitly in
 *                subclasses so `manager` carries a useful type.
 *
 * @example
 * ```ts
 * // Minimal Sequelize-style subclass
 * class OrmManager<E extends EntityBase>
 *     extends OrmManagerBase<E, Model<any, any>, Sequelize> {
 *
 *     async createOne(
 *         data: EntityCreationAttributes<E, CreationOptional<E>>
 *     ): Promise<Model<any, any>> {
 *         return this.manager.create(data);
 *     }
 *
 *     async deleteOne(id: number): Promise<boolean> {
 *         const n = await this.manager.destroy({ where: { id } });
 *         return n > 0;
 *     }
 *
 *     async destroyAll(where?: EntityQueryable<E>): Promise<number> {
 *         return this.manager.destroy({ where });
 *     }
 * }
 * ```
 */
export abstract class OrmManagerBase<
    E extends EntityBase,
    T,
    M = unknown
> {
    /**
     * @param manager The ORM-specific database manager instance (e.g.
     *                `Sequelize`, `PrismaClient`). Held as a public field
     *                so subclasses can reach the underlying connection.
     * @param dialect The active database dialect. Drives dialect-aware
     *                decisions in subclasses (converter selection, SQL
     *                flavor, etc.).
     */
    constructor(
        public manager: M,
        public dialect: DialectOptions
    ) {}

    /**
     * Insert a single new record.
     *
     * @param data Fields for the new record. Fields declared in
     *             {@link CreationOptional} or {@link CreationOptionalAlways}
     *             may be omitted (they are auto-generated by the
     *             database).
     * @returns The newly created ORM row / model (`T`). Whether this is
     *          a fully-typed entity or a raw ORM model depends on the
     *          subclass — see the subclass-specific docs.
     */
    public abstract createOne(
        data: EntityCreationAttributes<E, CreationOptional<E>>
    ): Promise<T>;

    /**
     * Delete a single record by primary key.
     *
     * @param id Numeric primary key of the record to delete.
     * @returns `true` when a record was actually removed, `false` when
     *          no matching record existed.
     */
    public abstract deleteOne(id: number): Promise<boolean>;

    /**
     * Delete every record matching the optional filter.
     *
     * @param where Optional {@link EntityQueryable} filter. When omitted
     *             (or `undefined`), **every** record of the entity is
     *             removed — use with care.
     * @returns The number of records deleted.
     */
    public abstract destroyAll(where?: EntityQueryable<E>): Promise<number>;
}
