import { TransformNullishToOptional } from '../Global'
import { EntityBase, EntityNoExternal, ExternalReferences } from './Root'
import { EntityTransform } from './Converters'
import { ConfigTypes } from '../Config'


/**
 * Fields that are optional during entity creation.
 * These are typically auto-generated by the database (id, created, updated timestamps).
 */
export type CreationOptionalAlways = 'id' | 'created' | 'updated' | 'active'

/**
 * Fieleds specific for each entity marked as optional.
 */
export type CreationOptional<E extends EntityBase> = keyof EntityNoExternal<E>

/**
 * Transform attributes type to the one that is accepted in creation process.
 */
export type EntityCreation<E extends EntityBase> = EntityTransform<E, ConfigTypes['entityCreationTransform']>

/**
 * Type for entity creation attributes.
 * Excludes external references.
 * Marks attributes as optional using {@link CreationOptionalAlways} and {@link CreationOptional}. 
 * Used when creating new records where some fields does not has to be provided.
 */
export type EntityCreationAttributes<
        E extends EntityBase, 
        O extends CreationOptional<E> = never> = 
    Omit<TransformNullishToOptional<EntityCreation<E>>, keyof ExternalReferences<E> | O | CreationOptionalAlways>
    & Partial<Pick<EntityCreation<E>, O | CreationOptionalAlways & keyof EntityCreation<E>>
> 

